# Weekly Report: 06/07/2019 -- 06/17/2019

## Brief: What was done previously
Previous work discovered multiple mechanisms to improve the accuracy of prediction. This week we quantify the perfomance of those methods and test them against a standard baseline.

## Experiments

1. Experiment 1: Prediction accuracy vs increased magnitude of sensor noise (fixed gausian per pixel noise)
2. Experiment 2: Prediction accuracy vs increasing number of missing sensor samples (entire patch - randomized drop-out)
3. Experiment 3: Prediction accuracy vs increasing number of sensor values (per pixel randomized drop-out)



## Summary of Main Results and Discussions
TODO


### Experiment 1 results and discussion
Put main result and conclusions here. Discuss importance/impact in terms of the project goals.

### Experiment 2: results and discussion
Put main result and conclusions here. Discuss importance/impact in terms of the project goals.


## Plan for next effort
What will be tested/extended from this week?
    

    


In [1]:
# import packages 
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as plt
import os

# Hypothesis 1

Begin testing relationship between predictive accuracy and fixed sensor noise

## Generating Fixed Noise

Encode the existing data with sample level noise:

In [1]:
# Test 1 code
import numpy as np

from src.predict_turbulence_recurrent import train
from src.dataLoader.turbulence import Turbulence, RANDOM_SEED, LARGE_DATASET

# Begin with 10% noise
np.random.seed(RANDOM_SEED)
noise_data = np.random.normal(size=(360, 279, 1000), scale=0.1)

loader = Turbulence(pred_length=20, dataset_idx=LARGE_DATASET, input_noise=noise_data, debug=True)

train(loader=loader, dataset_idx=LARGE_DATASET, num_batches=10)




C:\Users\brandon\source\orbitalMechanics
shape: (360, 279, 1000)
window_shape [50, 50, 40]
x size [50, 50, 20]
y size [-1, 50, 50, 20]
Number of parameter per sample of y: 100440
Example region: [[116 217 702]
 [ 50  50  20]
 [  0   0 722]
 [ 50  50   1]]
Instructions for updating:
Colocations handled automatically by placer.
Input shape: (20, ?, 2500)
Output shape: (20, ?, 50, 50)
Input shape: [20, None, 2500]
Instructions for updating:
This class is equivalent as tf.keras.layers.GRUCell, and will be replaced by that in Tensorflow 2.0.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
Padded input shape: [20, 64, 2500]
[20, 64, 250]
Instructions for updating:
Use keras.layers.dense instead.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:Summa

ValueError: slice index 59 of dimension 0 out of bounds. for 'strided_slice_6' (op: 'StridedSlice') with input shapes: [20,64,50,50], [4], [4], [4] and with computed input tensors: input[1] = <59 0 0 0>, input[2] = <60 0 0 0>, input[3] = <1 1 1 1>.

## Test 2

Test 2 blah blah ... define variables, etc.

In [1]:
# Test 2 code

# Hypothesis 2

Sample level dropout

# Test 1

Description of test 1 of hypothesis 2.


In [2]:
# Test 1, hyp 2 code